(module awful-picman ()

(import chicken scheme)
(declare (uses chicken-syntax))

;; Core units
(use irregex posix files srfi-1 srfi-13 extras data-structures setup-api ports)

;; Eggs
(use awful-sql-de-lite imlib2 spiffy simple-sha1 sql-de-lite json free-gettext)
(use (rename awful (debug awful-debug)))

;; Module generated by this egg
(use awful-picman-params)

(include "src/conf")
(include "src/renderers")
(include "src/image")
(include "src/utils")
(include "src/db")
(include "src/ajax-handlers")
(include "src/dispatcher")
(include "src/main")

) ;; end module
